name: 'Contribution stats report'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Generate Report
        uses: rootworkspace/organization-activity-report@main
        id: report
        with:
          token: ${{ secrets.ORG_STATS_TOKEN }}
          organization: 'rootworkspace'

      - name: Clone Stats Repository
        run: |
          git clone https://x-access-token:${{ secrets.ORG_STATS_TOKEN }}@github.com/rootworkspace/contribution-stats.git stats_repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate SVG Graph
        run: |
          python3 stats_repo/main.py
          
      - name: Commit and Push to Stats Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add contribution_graph.svg
          git commit -m "docs: update activity stats" || echo "No changes to commit"
          git push