name: 'Monthly activity report'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Calculate Rolling Dates
        id: dates
        run: |
          SINCE=$(date -d "31 days ago" +%Y-%m-%dT%H:%M:%SZ)
          UNTIL=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "since=$SINCE" >> $GITHUB_OUTPUT
          echo "until=$UNTIL" >> $GITHUB_OUTPUT

      - name: Generate Report
        uses: sorekz/user-activity-report@v1
        id: report
        with:
          token: ${{ secrets.ORG_STATS_TOKEN }}
          organization: 'rootworkspace'
          since: ${{ steps.dates.outputs.since }}
          until: ${{ steps.dates.outputs.until }}
          create-json: 'report.json'
          create-csv: 'report.csv'
      
      - name: Upload Activity Report
        uses: actions/upload-artifact@v4
        with:
          name: monthly-activity-report
          path: |
            *.csv
            *.json