name: 'Monthly activity report'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Report
        uses: rootworkspace/user-activity-report@main
        id: report
        with:
          token: ${{ secrets.ORG_STATS_TOKEN }}
          organization: 'rootworkspace'
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            report.json